#!/bin/sh

. /etc/init.d/functions

do_start() {
	/usr/sbin/cupsd -c /etc/cups/cupsd.conf -s /etc/cups/cups-files.conf
}

do_stop() {
	killproc cupsd
}

case "$1" in
  start)
	echo "Starting cups daemon"
	do_start
	;;
  stop)
	echo "Stopping cups daemon"
	do_stop
	;;
  restart|force-reload)
	echo "Restarting cups daemon"
	do_stop
	sleep 1
	do_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
