#!/bin/sh

. /etc/init.d/functions

do_start() {
	/usr/local/bin/samegame -platform eglfs &
}

do_stop() {
	killproc samegame
}

case "$1" in
  start)
	echo "Starting samegame app"
	do_start
	;;
  stop)
	echo "Stopping samegame app"
	do_stop
	;;
  restart|force-reload)
	echo "Restarting samegame app"
	do_stop
	sleep 1
	do_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
